### ISSUE TITLE
I can't catch exception

### ISSUE THREAD

**Issue by zstergios** [InitPHP/Socket#2]
Can you help?

( ! ) Fatal error: Uncaught InitPHP\Socket\Exception\SocketConnectionException: Socket Connection Error : 10060 vendor\initphp\socket\src\Client\TCP.php on line 55

            use \InitPHP\Socket\Socket;
            use \InitPHP\Socket\Exception\SocketConnectionException;
            use \InitPHP\Socket\Exception\SocketInvalidArgumentException;

		try
		{
			//error_reporting(0);
			@ini_set("default_socket_timeout",15);
			$this->client = Socket::client(Socket::TCP,$this->params['connectip'],$this->params['port']);
		}
		catch(Exception | Throwable | \SocketInvalidArgumentException | \SocketConnectionException $e)
		{
			$this->error=$e->getMessage();
			$this->setLog('connect error',$this->error);
			return false;
		}

**Comment by muhammetsafak** [comment]
This means it cannot connect to the socket. I will check it at a suitable time and update if there is an error.

**Comment by zstergios** [comment]
Yes I know, want to handle such errors, but can't catch the exception.

**Comment by muhammetsafak** [comment]
I understand, you are complaining about not being able to catch the error. The first error I see in your code is the "\\" symbol you use at the beginning of the SocketConnectionException and SocketInvalidArgumentException errors. Try updating your code as below.

```php
        use \InitPHP\Socket\Socket;
        use \InitPHP\Socket\Exception\SocketConnectionException;
        use \InitPHP\Socket\Exception\SocketInvalidArgumentException;
        use \Exception;
        use \Throwable;

	try
	{
		//error_reporting(0);
		@ini_set("default_socket_timeout",15);
		$this->client = Socket::client(Socket::TCP,$this->params['connectip'],$this->params['port']);
	}
	catch(Exception | Throwable | SocketInvalidArgumentException | SocketConnectionException $e)
	{
		$this->error=$e->getMessage();
		$this->setLog('connect error',$this->error);
		return false;
	}
```

**Comment by zstergios** [comment]
I have already tried it with and without. Can you please make your own tests?
My PHP is 7.4

**Comment by zstergios** [comment]
Final it's ok
